### ISSUE TITLE
Other output formatting issues

### ISSUE THREAD

**Issue by alertme-edwin** [jeemok/better-npm-audit#24]
When there are vulnerabilities found, the code does:

`process.exit(1);`

which causes output like this:

```
2 vulnerabilities found. Node security advisories: ####,####
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ########## audit: `node node_modules/better-npm-audit audit`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ############# audit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ##################/.npm/_logs/2021-05-20T13_48_02_404Z-debug.log
```

(with the hashes being my redactions).  The pull request said that it now exits "cleanly", so I'm wondering if my npm or terminal config is incorrect.

Similarly, I'm getting output like this:

```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       
0m│ ############                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=######                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
```

(with the hashes redacting the package name and version number), which suggests there is some problem with the buffering of the long output still.  The `0m` appears to be in a light grey text colour, but other than that I'm not getting any colours in the output.

I hope this is a valid issue, and I apologise for reporting so many in this fantastic package!

**Comment by jeemok** [comment]
yeah, I don't have test cases for the report output yet (I assume you're on npm v6). I added the coloring to the console log as it seems to "pollute" the rest of the message with the same color (I think because it got stopped before it finished), it looks like this:

<img width="880" alt="Screen Shot 2021-05-23 at 5 44 02 PM" src="https://user-images.githubusercontent.com/26216852/119255492-b77d8800-bbee-11eb-8e62-078eb83f625e.png">

so I added the coloring to set manually:

<img width="766" alt="Screen Shot 2021-05-23 at 5 46 50 PM" src="https://user-images.githubusercontent.com/26216852/119255547-02979b00-bbef-11eb-8502-34b6ccf8cf85.png">

it's not a big deal and I can remove the coloring if it is causing trouble than its helping :) to make sure I understand your issue clearly, do you mind sharing a screenshot?

**Comment by jeemok** [comment]
and thank you for raising issues and helping to give suggestions! I'll try my best to improve this library :)

**Comment by jeemok** [comment]
@alertme-edwin can you try with `v1.9.2`?

**Comment by alertme-edwin** [comment]
`v1.9.2` fixes the weird line-break issue, thank you so much!

I don't think I was having problems with the presence of colours, as such.  The line-break issue just looked more strange when it was interacting with the sequences responsible for the colours.

I'm happy for there to be more use of colours/bold like the basic `npm audit` provides.

(Yes, I'm still using npm v6, which I hope is okay).  I probably shouldn't have put two formatting issues in the same ticket, so I might create a new one later about the `npm ERR! code ELIFECYCLE` user experience.  For now, though, I'm really happy with this new version.

**Comment by jeemok** [comment]
yeah I realized it was not efficient to display the output immediately when we receive the buffer. Thanks for raising this issue! and feel free to suggest more areas to improve :) happy that you like this version
